Add bridge configs for PostPublicationEvents (kafka->MSK) and Publica…
Financial-Times/coco-kafka-bridge pull request #94
Opened 2022-04-01 14:09 UTC by dtvalk-ov

Add bridge configs for PostPublicationEvents (kafka->MSK) and PublictionNotificationEvents(MSK->kafka)

# Description

## Why

[Jira Ticket](https://financialtimes.atlassian.net/browse/UPPSF-3086)

## Anything, in particular, you'd like to highlight to reviewers

Mention here sections of code which you would like reviewers to pay extra attention to .E.g

_Would appreciate a second pair of eyes on the test_  
_I am not quite sure how this bit works_  
_Is there a better library for doing x_  

## Scope and particulars of this PR (Please tick all that apply)

- [ ] Tech hygiene (dependency updating & other tech debt)
- [ ] Bug fix
- [x] Feature
- [ ] Documentation
- [ ] Breaking change
- [ ] Minor change (e.g. fixing a typo, adding config)

___
This Pull Request follows the rules described in our [Pull Requests Guide](https://github.com/Financial-Times/upp-docs/tree/master/guides/pr-guide)

2022-04-05 09:35 UTC, atanasdinov requested changes
LGTM! I'd also suggest removing the old bridges (for `CombinedPostPublicationEvents` and `ForcedCombinedPostPublicationEvents` topics) in this PR.

Ideally, we'd be only keeping the currently relevant bridges so it's easier to adjust the EKS provisioners if needed.

2022-04-05 11:29 UTC, MiroslavGatsanoga submitted a review, later dismissed

2022-04-05 11:58 UTC, atanasdinov submitted a review, later dismissed

2022-04-05 12:09 UTC, martin-stanchev submitted a review, later dismissed

2022-04-11 07:53 UTC, atanasdinov approved these changes

2022-04-11 10:52 UTC, martin-stanchev approved these changes

2022-04-11 10:53 UTC, merged